name = "dcf"
description = "Ada 2012 library for document container files, Zip-based archive files"
version = "2.0.2"
website = "https://github.com/onox/dcf-ada"
licenses = "MIT"
tags = ["zip", "document", "container"]

authors = ["onox", "Gautier de Montmollin"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

configuration.disabled = true
