name = "dcf"
description = "Ada 2012 library for document container files, a Zip-based format"
long-description = "An Ada 2012 library for document container files, a Zip-based archive format standardized in ISO/IEC 21320-1:2015"
version = "2.0.2"
website = "https://github.com/onox/dcf-ada"
licenses = "MIT"
tags = ["zip", "document", "container"]

authors = ["onox", "Gautier de Montmollin"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]
